---
title: "Shiny's Biorhythm"
author: "by **Eduardo B. Díez**"
date: "Developing Data Products --- Peer Assessments Project"
output:
  ioslides_presentation:
    keep_md: yes
    logo: DevelopingDataProducts.jpg
    transition: faster
runtime: shiny
---

## Shiny's Biorhythm: The application

**Shiny's Biorhythm** is a shiny app to complete the project for the course **Developing Data Products**. The application includes many features among which are some that develop below.

The application shows severals modifications in the html stile of the default shiny widgets. Good examples are the background color changed from gray to pink and the headers used inside the `sidebarPanel`, all of them done with the `HTML()` function. Also there are some other HTML editions as the separator lines in both the `sidepanel` as in the `mainpanel`.

In the `sidepanel()`, from the `ui.R file`, are defined three inputs. Two of them of type  `dateInput()` to introduce the birthday or stating point of the calculations and the one for the date that correspond with our interest point of the prediction usually the courrent day. 

The way to introduce the date is quite simple; once click in the imput area a window-calendar is displayed where the user can click at the two lateral arrows to get a fast displacement between the months one by one.

---

In addition, by clicking on the year number, changes the year one by one, but one more click on the year number will produce to change from one decade to the next, getting a faster displacement. Once selected the year, the window-calendar shows the months and after selecting the month, all the days are shown to choose one. 

The last entry corresponds to the number of days to be displayed on the x-axis in the plot, usually a week ahead. To change the value user move the mark from side to side, from a minimum of three to a maximum of eleven.

All three previous entries, from `ui.R` are used reactively in the calculations in `server.R` and the results shown in the plot. Therefore, a change in any of the three inputs will produce a change in the plot. 

Also three formulas are calculated and displayed in the plot as three lines. Each one responds to a sin curve form of the type $sin(\frac{2 \pi T}{K})$ where $T \space$ is the amount of days between the two input dates and $K \space$ is a constant  with a different value for each biocurve.

## Shiny's Biorhythm: The documentation

The documentation has only one chunk with R code that makes use of the function `shinyAppDir()` in order to embed the entire application inside the own document in the next slide, making it really interactive. 

The R markdown source code that produce this presentation ---the one you're reading now--- and also the R code from the `ui.R` and `server.R` files, both are fully comented and they must be considered as part of the documentation of the whole project and they are accesibles ---the sources--- in this [GitHub repository]().

Finally, both the application as well as the html slides documentation running and accesible directly in the `shinyapps.io` server:

<div class="centered">

<a href="http://turpial.shinyapps.io/VerControl/">The shiny application</a>

<a href="http://turpial.shinyapps.io/SlidesVerControl/SlidesVerControl.Rmd#1">The slides documentation</a>

</div>


## Shiny's Biorhythm: Embeded Here!

The entire Shiny's Biorhythm application is embeded in the document making possible the full use of it. Also the application can be executed from this [shinyapps.io](<http://turpial.shinyapps.io/VerControl/>) repository. Enjoy it!

<hr>

```{r, echo=FALSE}
shinyAppDir(appDir="./VerControl",
 # system.file("examples/06_tabsets", package="shiny"),
  options=list(
    width="100%", height="100%"
  )
)
```


